modLoader="javafml"
loaderVersion="[36,)"
license="https://biggestxuan.top/emcworld/l"
issueTrackerURL="https://github.com/BiggestXuan/EMCworld/issues"
[[mods]]
modId="emcworld"
version="1.3.1"
displayName="EMCWorld"
logoFile=""
authors="Biggest_Xuan"
credits="Dctor_0415,sdxhop"
description='''
'''
[[dependencies.emcworld]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"
[[dependencies.emcworld]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
