
[Client]
	#Attempts to translate structure names before fixing the unlocalized names. Translations may not be available for all structures.
	translateStructureNames = true
	#The side for information rendered on the HUD. Ex: LEFT, RIGHT
	#Allowed Values: LEFT, RIGHT
	overlaySide = "LEFT"
	#Displays Explorer's Compass information on the HUD even while chat is open.
	displayWithChatOpen = true
	#The line offset for information rendered on the HUD.
	#Range: 0 ~ 50
	overlayLineOffset = 1

