
[mobs]

	[mobs.creepers]
		"Creepers drop Creeper Spores after they die from an explosion" = true
		"Creepie explosions destroy blocks" = false
		"Creeper explosions spawn creepies" = false
		"Creeper explosions destroy blocks" = true

	[mobs.illagers]
		#When killed by projectiles, evokers use a totem of undying
		#This restores 2 health and gives them a projectile-proof shield for 30 seconds
		#When their shield runs out, evokers cannot use totems for another 90 seconds
		"Evokers use totems" = true
		"Vex health is reduced to 2" = true
		#Illagers with banners will no longer give Bad Omen when you kill them
		#Instead, you will have to place and burn the banner that they drop with flint and steel or a fire charge
		"Illagers no longer give Bad Omen on death" = false

